SOURCES=\
src/UnitTests.cpp\
src/FileReader.cpp\
src/ParticleContainer.cpp\
src/MaxwellBoltzmannDistribution.cpp\
src/StateWriter.cpp\
src/Particle.cpp\
src/ParticleGenerator.cpp\
src/outputWriter/XYZWriter.cpp\
src/outputWriter/VTKWriter.cpp\
src/MolSim.cpp\
src/Thermostat.cpp\
src/config.cxx\
src/outputWriter/vtk-unstructured.cxx\
src/simulation.cxx\
