SOURCES=\
src/FileReader.cpp\
src/MaxwellBoltzmannDistribution.cpp\
src/MolSim.cpp\
src/outputWriter/vtk-unstructured.cpp\
src/outputWriter/VTKWriter.cpp\
src/outputWriter/XYZWriter.cpp\
src/Particle.cpp\
src/ParticleContainer.cpp\
src/ParticleGenerator.cpp\
src/Thermostat.cpp\
src/UnitTests.cpp\
