SOURCES=\
src/FileReader.cpp\
src/MaxwellBoltzmannDistribution.cpp\
src/MolSim.cpp\
src/outputWriter/vtk-unstructured.cpp\
src/outputWriter/VTKWriter.cpp\
src/outputWriter/XYZWriter.cpp\
src/Particle.cpp\
src/ParticleContainer.cpp\
src/ParticleGenerator.cpp\
src/UnitTests.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/DOMException.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/DOMLSException.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/DOMRangeException.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/DOMXPathException.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMNodeImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMNodeIteratorImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMNodeListImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMNodeVector.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMNormalizer.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMNotationImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMParentNode.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMProcessingInstructionImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMRangeImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMStringListImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMStringPool.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMTextImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMTreeWalkerImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMTypeInfoImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMXPathExpressionImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMXPathNSResolverImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMXPathResultImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/XSDElementNSImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMAttrImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMAttrMapImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMAttrNSImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMCDATASectionImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMCharacterDataImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMChildNode.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMCommentImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMConfigurationImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMDeepNodeListImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMDocumentFragmentImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMDocumentImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMDocumentTypeImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMElementImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMElementNSImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMEntityImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMEntityReferenceImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMErrorImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMImplementationImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMImplementationListImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMImplementationRegistry.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMLocatorImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMLSInputImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMLSOutputImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMLSSerializerImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMNamedNodeMapImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/dom/impl/DOMNodeIDMap.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/XMLSchemaDescription.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/XMLValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/BinOutputStream.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/LocalFileFormatTarget.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/LocalFileInputSource.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/MemBufFormatTarget.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/MemBufInputSource.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/psvi/PSVIAttribute.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/psvi/PSVIAttributeList.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/psvi/PSVIElement.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/psvi/PSVIItem.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/psvi/XSAnnotation.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/psvi/XSAttributeDeclaration.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/psvi/XSAttributeGroupDefinition.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/psvi/XSAttributeUse.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/psvi/XSComplexTypeDefinition.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/psvi/XSElementDeclaration.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/psvi/XSFacet.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/psvi/XSIDCDefinition.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/psvi/XSModel.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/psvi/XSModelGroup.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/psvi/XSModelGroupDefinition.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/psvi/XSMultiValueFacet.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/psvi/XSNamespaceItem.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/psvi/XSNotationDeclaration.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/psvi/XSObject.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/psvi/XSParticle.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/psvi/XSSimpleTypeDefinition.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/psvi/XSTypeDefinition.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/psvi/XSValue.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/psvi/XSWildcard.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/StdInInputSource.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/StdOutFormatTarget.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/URLInputSource.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/Wrapper4DOMLSInput.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/Wrapper4InputSource.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/XMLAttDef.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/XMLAttDefList.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/XMLAttr.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/XMLBuffer.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/XMLBufferMgr.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/XMLContentModel.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/XMLDTDDescription.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/XMLElementDecl.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/XMLEntityDecl.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/XMLFormatter.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/XMLGrammarDescription.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/XMLGrammarPoolImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/XMLNotationDecl.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/XMLRecognizer.cpp\
src/xerces-c-3.1.1/src/xercesc/framework/XMLRefInfo.cpp\
src/xerces-c-3.1.1/src/xercesc/internal/BinFileOutputStream.cpp\
src/xerces-c-3.1.1/src/xercesc/internal/BinMemOutputStream.cpp\
src/xerces-c-3.1.1/src/xercesc/internal/DGXMLScanner.cpp\
src/xerces-c-3.1.1/src/xercesc/internal/ElemStack.cpp\
src/xerces-c-3.1.1/src/xercesc/internal/IGXMLScanner.cpp\
src/xerces-c-3.1.1/src/xercesc/internal/IGXMLScanner2.cpp\
src/xerces-c-3.1.1/src/xercesc/internal/MemoryManagerImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/internal/ReaderMgr.cpp\
src/xerces-c-3.1.1/src/xercesc/internal/SGXMLScanner.cpp\
src/xerces-c-3.1.1/src/xercesc/internal/ValidationContextImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/internal/VecAttributesImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/internal/VecAttrListImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/internal/WFXMLScanner.cpp\
src/xerces-c-3.1.1/src/xercesc/internal/XMLReader.cpp\
src/xerces-c-3.1.1/src/xercesc/internal/XMLScanner.cpp\
src/xerces-c-3.1.1/src/xercesc/internal/XMLScannerResolver.cpp\
src/xerces-c-3.1.1/src/xercesc/internal/XProtoType.cpp\
src/xerces-c-3.1.1/src/xercesc/internal/XSAXMLScanner.cpp\
src/xerces-c-3.1.1/src/xercesc/internal/XSerializeEngine.cpp\
src/xerces-c-3.1.1/src/xercesc/internal/XSObjectFactory.cpp\
src/xerces-c-3.1.1/src/xercesc/internal/XTemplateSerializer.cpp\
src/xerces-c-3.1.1/src/xercesc/parsers/AbstractDOMParser.cpp\
src/xerces-c-3.1.1/src/xercesc/parsers/DOMLSParserImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/parsers/SAX2XMLFilterImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/parsers/SAX2XMLReaderImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/parsers/SAXParser.cpp\
src/xerces-c-3.1.1/src/xercesc/parsers/XercesDOMParser.cpp\
src/xerces-c-3.1.1/src/xercesc/sax/Dummy.cpp\
src/xerces-c-3.1.1/src/xercesc/sax/InputSource.cpp\
src/xerces-c-3.1.1/src/xercesc/sax/SAXException.cpp\
src/xerces-c-3.1.1/src/xercesc/sax/SAXParseException.cpp\
src/xerces-c-3.1.1/src/xercesc/sax2/sax2Dummy.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/common/AllContentModel.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/common/CMAny.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/common/CMBinaryOp.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/common/CMUnaryOp.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/common/ContentLeafNameTypeVector.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/common/ContentSpecNode.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/common/DFAContentModel.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/common/Grammar.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/common/GrammarResolver.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/common/MixedContentModel.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/common/SimpleContentModel.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/NCNameDatatypeValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/NOTATIONDatatypeValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/QNameDatatypeValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/StringDatatypeValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/TimeDatatypeValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/UnionDatatypeValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/XMLCanRepGroup.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/YearDatatypeValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/YearMonthDatatypeValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/AbstractNumericFacetValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/AbstractNumericValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/AbstractStringValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/AnySimpleTypeDatatypeValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/AnyURIDatatypeValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/Base64BinaryDatatypeValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/BooleanDatatypeValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/DatatypeValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/DatatypeValidatorFactory.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/DateDatatypeValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/DateTimeDatatypeValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/DateTimeValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/DayDatatypeValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/DecimalDatatypeValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/DoubleDatatypeValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/DurationDatatypeValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/ENTITYDatatypeValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/FloatDatatypeValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/HexBinaryDatatypeValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/IDDatatypeValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/IDREFDatatypeValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/ListDatatypeValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/MonthDatatypeValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/MonthDayDatatypeValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/datatype/NameDatatypeValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/DTD/DTDAttDef.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/DTD/DTDAttDefList.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/DTD/DTDElementDecl.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/DTD/DTDEntityDecl.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/DTD/DTDGrammar.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/DTD/DTDScanner.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/DTD/DTDValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/DTD/XMLDTDDescriptionImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/ComplexTypeInfo.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/GeneralAttributeCheck.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/identity/FieldActivator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/identity/FieldValueMap.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/identity/IC_Field.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/identity/IC_Key.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/identity/IC_KeyRef.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/identity/IC_Selector.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/identity/IC_Unique.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/identity/IdentityConstraint.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/identity/IdentityConstraintHandler.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/identity/ValueStore.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/identity/ValueStoreCache.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/identity/XercesXPath.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/identity/XPathMatcher.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/identity/XPathMatcherStack.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/identity/XPathSymbols.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/NamespaceScope.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/SchemaAttDef.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/SchemaAttDefList.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/SchemaElementDecl.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/SchemaGrammar.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/SchemaInfo.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/SchemaSymbols.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/SchemaValidator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/SubstitutionGroupComparator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/TraverseSchema.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/XercesAttGroupInfo.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/XercesElementWildcard.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/XercesGroupInfo.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/XMLSchemaDescriptionImpl.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/XSDDOMParser.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/XSDErrorReporter.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/XSDLocator.cpp\
src/xerces-c-3.1.1/src/xercesc/validators/schema/XUtil.cpp\
src/xerces-c-3.1.1/src/xercesc/xinclude/XIncludeDOMDocumentProcessor.cpp\
src/xerces-c-3.1.1/src/xercesc/xinclude/XIncludeLocation.cpp\
src/xerces-c-3.1.1/src/xercesc/xinclude/XIncludeUtils.cpp\
